//main.v

//main entry point for code. Initially this will be used to check out all the handlers, eventually this will be dynamically generated by "SAP"

//uart input handler

//uart output handler

module main (
	clk,
	rst,
);

uart_input_handler uih(
	.clk(clk),
	.rst(rst),
	.byte_available(byte_available),
	.byte(in_byte),
	.command(wb_command),
	.address(wb_address_in),
	.data(wb_data_in),
	.ready(ih_ready));

uart_output_handler uoh(
	.clk(clk),
	.rst(rst),
	.byte(out_byte),
	.status(wb_status),
	.address(wb_address_out),
	.data(wb_data_out),
	.send_en(uoh_en),
	.uart_ready(uart_ready)
	.handler_ready(oh_ready),
	.uart_byte_en(uart_byte_en),
	.finished(oh_finished));
